controller_manager:
  ros__parameters:
    update_rate: 100                    # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:              # ← controller name; must match spawner
      type: diff_drive_controller/DiffDriveController

      left_wheel_names:  ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      wheel_separation: 0.626
      wheel_radius:     0.10

      open_loop:        true            # you run open-loop
      publish_rate:     50.0
      cmd_vel_timeout:  0.5
      enable_odom_tf:   true
